language: node_js
node_js: 12.16.1

addons:
  apt:
    packages:
      - libgconf-2-4

install:
  - npm install 
cache:  
  npm: true
  directories:
    - ~/.npm 
script:
  - yarn build
script:
  - npm run build

deploy:
  provider: netlify 
  site: 0e42a2dd-2b71-4cb4-ba04-5950e1d1e631
  auth: Hm3Nr8eJoFi1GzwTWPCJCQQ9a3NN1NVi5idg6pvvzTQ
  edge: true
