language: node_js
node_js:
  -10.15.0
cache:  
  npm: true
  directories:
    - ~/.npm 
before_script:
  - npm run develop:ci -- --silent &
script:
  - set -e
  - npm run build

deploy:
  provider: netlify 
  site: https://mnrypshop.netlify.com
  auth: Hm3Nr8eJoFi1GzwTWPCJCQQ9a3NN1NVi5idg6pvvzTQ
  edge: true
