export type icons =
    | 'Accessories'
    | 'BathOil'
    | 'BeautyHealth'
    | 'Beverage'
    | 'Breakfast'
    | 'Cooking'
    | 'Dairy'
    | 'Deodorent'
    | 'Eyes'
    | 'Face'
    | 'FacialCare'
    | 'FruitsVegetable'
    | 'HandBags'
    | 'HomeCleaning'
    | 'LaptopBags'
    | 'Lips'
    | 'MeatFish'
    | 'OuterWear'
    | 'Pants'
    | 'Purse'
    | 'ShavingNeeds'
    | 'Shirts'
    | 'ShoulderBags'
    | 'Skirts'
    | 'Snacks'
    | 'Tops'
    | 'Wallet'
    | 'WomenDress'
    | 'OralCare'
    | 'PetCare';

export type Dict<T> = Record<icons, T>;
